/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bidangdantransform;

/**
 *
 * @author TOSHIBA
 */
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

public class BidangTrans extends javax.swing.JFrame {

    int x1, y1, x2, y2, x3, y3, x4, y4, state, sx, sy, tlx, tly, sh, deg;
    float sc;
    int wSize = 480 / 2, grid = 20;
    /**
     * Creates new form BidangTrans
     */
    public BidangTrans() {
        initComponents();
        jScrollPane1.setViewportView(new SistemUtama());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btn_addRect = new javax.swing.JButton();
        lbl_rpointA = new javax.swing.JLabel();
        fld_x1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fld_y1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ukuran = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_tpointA = new javax.swing.JLabel();
        fld_tx1 = new javax.swing.JTextField();
        fld_ty1 = new javax.swing.JTextField();
        lbl_tpointB = new javax.swing.JLabel();
        fld_tx2 = new javax.swing.JTextField();
        fld_ty2 = new javax.swing.JTextField();
        lbl_tpointC = new javax.swing.JLabel();
        fld_tx3 = new javax.swing.JTextField();
        fld_ty3 = new javax.swing.JTextField();
        btn_addTri = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        fld_tlx = new javax.swing.JTextField();
        fld_tly = new javax.swing.JTextField();
        lbl_tlx = new javax.swing.JLabel();
        lbl_tly = new javax.swing.JLabel();
        btn_trans = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_reflectX = new javax.swing.JButton();
        btn_reflectC = new javax.swing.JButton();
        btn_reflectY = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        fld_deg = new javax.swing.JTextField();
        btn_rotate = new javax.swing.JButton();
        lbl_deg = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        fld_scx = new javax.swing.JTextField();
        btn_scale = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        fld_sh = new javax.swing.JTextField();
        btn_shearX = new javax.swing.JButton();
        btn_shearY = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(480, 480));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane2.setFocusable(false);
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(220, 230));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_addRect.setBackground(new java.awt.Color(153, 255, 255));
        btn_addRect.setText("TAMPILKAN PERSEGI");
        btn_addRect.setFocusable(false);
        btn_addRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addRectActionPerformed(evt);
            }
        });

        lbl_rpointA.setText("X awal");

        fld_x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_x1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Y awal");

        fld_y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_y1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Range");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lbl_rpointA))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_y1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_x1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_addRect)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_rpointA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fld_x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_addRect)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Rectangle", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_tpointA.setText("Titik B");

        fld_tx1.setPreferredSize(new java.awt.Dimension(90, 20));

        fld_ty1.setPreferredSize(new java.awt.Dimension(90, 20));

        lbl_tpointB.setText("Titik A");

        fld_tx2.setPreferredSize(new java.awt.Dimension(90, 20));

        fld_ty2.setPreferredSize(new java.awt.Dimension(90, 20));

        lbl_tpointC.setText("Titik C");

        fld_tx3.setPreferredSize(new java.awt.Dimension(90, 20));

        fld_ty3.setPreferredSize(new java.awt.Dimension(90, 20));

        btn_addTri.setBackground(new java.awt.Color(204, 255, 255));
        btn_addTri.setText("TAMPILKAN SEGITIGA");
        btn_addTri.setFocusable(false);
        btn_addTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(fld_ty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fld_ty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tpointA)
                            .addComponent(fld_tx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tpointC)
                            .addComponent(fld_tx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_addTri))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_ty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_tx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tpointB))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tpointB)
                .addGap(1, 1, 1)
                .addComponent(fld_tx1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_ty1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tpointC)
                    .addComponent(lbl_tpointA))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_tx3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_tx2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_ty3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ty2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btn_addTri)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Triangle", jPanel3);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(220, 120));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        fld_tlx.setPreferredSize(new java.awt.Dimension(90, 20));

        fld_tly.setPreferredSize(new java.awt.Dimension(90, 20));

        lbl_tlx.setText("X");

        lbl_tly.setText("Y");

        btn_trans.setBackground(new java.awt.Color(204, 255, 255));
        btn_trans.setText("TRANSLASI");
        btn_trans.setFocusable(false);
        btn_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fld_tlx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tlx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fld_tly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tly))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_trans, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tlx)
                    .addComponent(lbl_tly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fld_tlx, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(fld_tly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_trans)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Translate", jPanel5);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btn_reflectX.setBackground(new java.awt.Color(204, 255, 255));
        btn_reflectX.setText("Sumbu X");
        btn_reflectX.setFocusable(false);
        btn_reflectX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reflectXActionPerformed(evt);
            }
        });

        btn_reflectC.setBackground(new java.awt.Color(204, 255, 255));
        btn_reflectC.setText("Pusat Koordinat");
        btn_reflectC.setFocusable(false);
        btn_reflectC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reflectCActionPerformed(evt);
            }
        });

        btn_reflectY.setBackground(new java.awt.Color(204, 255, 255));
        btn_reflectY.setText("Sumbu Y");
        btn_reflectY.setFocusable(false);
        btn_reflectY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reflectYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_reflectX, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_reflectY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_reflectC, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_reflectX)
                    .addComponent(btn_reflectY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reflectC)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reflection", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        fld_deg.setPreferredSize(new java.awt.Dimension(90, 20));

        btn_rotate.setBackground(new java.awt.Color(204, 255, 255));
        btn_rotate.setText("ROTASI");
        btn_rotate.setFocusable(false);
        btn_rotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rotateActionPerformed(evt);
            }
        });

        lbl_deg.setText("Sudut (Derajat)");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_deg)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fld_deg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_rotate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbl_deg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_deg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_rotate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rotate", jPanel9);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        fld_scx.setPreferredSize(new java.awt.Dimension(90, 20));

        btn_scale.setBackground(new java.awt.Color(217, 83, 79));
        btn_scale.setForeground(new java.awt.Color(255, 255, 255));
        btn_scale.setText("Scale");
        btn_scale.setFocusable(false);
        btn_scale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fld_scx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_scale, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fld_scx, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_scale)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Scale", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        fld_sh.setPreferredSize(new java.awt.Dimension(90, 20));

        btn_shearX.setBackground(new java.awt.Color(217, 83, 79));
        btn_shearX.setForeground(new java.awt.Color(255, 255, 255));
        btn_shearX.setText("X Axis");
        btn_shearX.setFocusable(false);
        btn_shearX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shearXActionPerformed(evt);
            }
        });

        btn_shearY.setBackground(new java.awt.Color(217, 83, 79));
        btn_shearY.setForeground(new java.awt.Color(255, 255, 255));
        btn_shearY.setText("Y Axis");
        btn_shearY.setFocusable(false);
        btn_shearY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shearYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(fld_sh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_shearX, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_shearY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fld_sh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_shearX)
                    .addComponent(btn_shearY))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Shear", jPanel7);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("BIDANG DAN TRANSFORMASI BIDANG");

        jButton1.setText("HAPUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addRectActionPerformed

        try {
            int sbX = Integer.parseInt(fld_x1.getText());
            int sbY = Integer.parseInt(fld_y1.getText());
            int sisi = Integer.parseInt(ukuran.getText());
            jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, sisi, 5));
            state = 1;
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_addRectActionPerformed

    private void fld_x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_x1ActionPerformed

    private void fld_y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_y1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_y1ActionPerformed

    private void btn_addTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addTriActionPerformed
        try {
            x1 = Integer.parseInt(fld_tx1.getText());
            x2 = Integer.parseInt(fld_tx2.getText());
            x3 = Integer.parseInt(fld_tx3.getText());

            y1 = Integer.parseInt(fld_ty1.getText());
            y2 = Integer.parseInt(fld_ty2.getText());
            y3 = Integer.parseInt(fld_ty3.getText());

            int x[] = {x1 * grid + wSize, x2 * grid + wSize, x3 * grid + wSize};
            int y[] = {wSize - grid * y1, wSize - grid * y2, wSize - grid * y3};

            jScrollPane1.setViewportView(new SistemUtama(x, y, 8, x1,x2,x3,y1,y2,y3));
            state=2;

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_addTriActionPerformed

    private void btn_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transActionPerformed
        if (state == 1) {
            try {
                int sbX = Integer.parseInt(fld_x1.getText());
                int sbY = Integer.parseInt(fld_y1.getText());
                int xT = Integer.parseInt(fld_tlx.getText());
                int yT = Integer.parseInt(fld_tly.getText());
                int sisi = Integer.parseInt(ukuran.getText());
                jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, xT, yT,sisi, 6));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong");
            }
        }
        if (state == 2) {
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());

                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());

                int xT = Integer.parseInt(fld_tlx.getText());
                int yT = Integer.parseInt(fld_tly.getText());

                int x[] = {x1 * grid + wSize, x2 * grid + wSize, x3 * grid + wSize};
                int y[] = {wSize - grid * y1, wSize - grid * y2, wSize - grid * y3};

                int xTs[] = {(x1+xT) * grid + wSize, (x2 + xT) * grid + wSize, (x3+xT) * grid + wSize};
                int yTs[] = {wSize - grid * (y1+yT), wSize - grid * (y2+yT), wSize - grid * (y3+yT)};
                jScrollPane1.setViewportView(new SistemUtama(x, y, xTs, yTs,9,x1,x2,x3,y1,y2,y3,xT, yT, -1));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_transActionPerformed

    private void btn_reflectXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reflectXActionPerformed
        if (state == 1) {
            try {
                int sbX = Integer.parseInt(fld_x1.getText());
                int sbY = Integer.parseInt(fld_y1.getText());
                int sisi = Integer.parseInt(ukuran.getText());
                jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, sisi, 18));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 2) {
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());

                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                jScrollPane1.setViewportView(new SistemUtama(x1,x2,x3,y1,y2,y3, -1, 25));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong");
            }
        }
    }//GEN-LAST:event_btn_reflectXActionPerformed

    private void btn_reflectCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reflectCActionPerformed
        if (state == 1) {
            try {
                int sbX = Integer.parseInt(fld_x1.getText());
                int sbY = Integer.parseInt(fld_y1.getText());
                int sisi = Integer.parseInt(ukuran.getText());
                jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, sisi, 20));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 2) {
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());

                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                jScrollPane1.setViewportView(new SistemUtama(x1,x2,x3,y1,y2,y3, -1, 27));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi fForm yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_reflectCActionPerformed

    private void btn_reflectYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reflectYActionPerformed
        if (state == 1) {
            try {
                int sbX = Integer.parseInt(fld_x1.getText());
                int sbY = Integer.parseInt(fld_y1.getText());
                int sisi = Integer.parseInt(ukuran.getText());
                jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, sisi, 19));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 2) {
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());

                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                jScrollPane1.setViewportView(new SistemUtama(x1,x2,x3,y1,y2,y3, -1, 26));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_reflectYActionPerformed

    private void btn_rotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rotateActionPerformed
        if (state == 1) {
            try {
                int sbX = Integer.parseInt(fld_x1.getText());
                int sbY = Integer.parseInt(fld_y1.getText());
                int sisi = Integer.parseInt(ukuran.getText());
                float sudutnya = Integer.parseInt(fld_deg.getText());
                jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, sudutnya, sisi, 7));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }

        }
        if (state == 2) {
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());

                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                int sudutnya = Integer.parseInt(fld_deg.getText());
                jScrollPane1.setViewportView(new SistemUtama(x1,x2,x3,y1,y2,y3, sudutnya, 22));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_rotateActionPerformed

    private void btn_scaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scaleActionPerformed
        if (state == 1) {
            try {
                int sbX = Integer.parseInt(fld_x1.getText());
                int sbY = Integer.parseInt(fld_y1.getText());
                float kali = Float.parseFloat(fld_scx.getText());
                int sisi = Integer.parseInt(ukuran.getText());
                jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, Math.abs(kali), sisi, 12));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 2) {
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());

                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                float kali = Float.parseFloat(fld_scx.getText());
                jScrollPane1.setViewportView(new SistemUtama(x1,x2,x3,y1,y2,y3, Math.abs(kali), 21));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_scaleActionPerformed

    private void btn_shearXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shearXActionPerformed
        if (state == 1) {

            try {
                int sbX = Integer.parseInt(fld_x1.getText());
                int sbY = Integer.parseInt(fld_y1.getText());
                int sisi = Integer.parseInt(ukuran.getText());
                float besarShearX = Integer.parseInt(fld_sh.getText());
                jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, besarShearX, sisi, 16));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 2) {
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());

                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                int besarShearX = Integer.parseInt(fld_sh.getText());
                jScrollPane1.setViewportView(new SistemUtama(x1,x2,x3,y1,y2,y3, besarShearX, 23));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_shearXActionPerformed

    private void btn_shearYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shearYActionPerformed
        if (state == 1) {
            try {
                int sbX = Integer.parseInt(fld_x1.getText());
                int sbY = Integer.parseInt(fld_y1.getText());
                int sisi = Integer.parseInt(ukuran.getText());
                float besarShearX = Integer.parseInt(fld_sh.getText());
                jScrollPane1.setViewportView(new SistemUtama(sbX, sbY, besarShearX, sisi, 17));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 2) {
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());

                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                int besarShearX = Integer.parseInt(fld_sh.getText());
                jScrollPane1.setViewportView(new SistemUtama(x1,x2,x3,y1,y2,y3, besarShearX, 24));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_shearYActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setViewportView(new SistemUtama());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BidangTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BidangTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BidangTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BidangTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addRect;
    private javax.swing.JButton btn_addTri;
    private javax.swing.JButton btn_reflectC;
    private javax.swing.JButton btn_reflectX;
    private javax.swing.JButton btn_reflectY;
    private javax.swing.JButton btn_rotate;
    private javax.swing.JButton btn_scale;
    private javax.swing.JButton btn_shearX;
    private javax.swing.JButton btn_shearY;
    private javax.swing.JButton btn_trans;
    private javax.swing.JTextField fld_deg;
    private javax.swing.JTextField fld_scx;
    private javax.swing.JTextField fld_sh;
    private javax.swing.JTextField fld_tlx;
    private javax.swing.JTextField fld_tly;
    private javax.swing.JTextField fld_tx1;
    private javax.swing.JTextField fld_tx2;
    private javax.swing.JTextField fld_tx3;
    private javax.swing.JTextField fld_ty1;
    private javax.swing.JTextField fld_ty2;
    private javax.swing.JTextField fld_ty3;
    private javax.swing.JTextField fld_x1;
    private javax.swing.JTextField fld_y1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_deg;
    private javax.swing.JLabel lbl_rpointA;
    private javax.swing.JLabel lbl_tlx;
    private javax.swing.JLabel lbl_tly;
    private javax.swing.JLabel lbl_tpointA;
    private javax.swing.JLabel lbl_tpointB;
    private javax.swing.JLabel lbl_tpointC;
    private javax.swing.JTextField ukuran;
    // End of variables declaration//GEN-END:variables
}
