/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bidangdantransform;

import javax.swing.JOptionPane;

/**
 *
 * @author Nurcahyo
 */
public class Clipping extends javax.swing.JFrame {

    int x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, d1, d2, d3, state;
    float sc;
    int wSize = 480 / 2, grid = 20;

    /**
     * Creates new form ShapeUI
     */
    public Clipping() {
        initComponents();
        jScrollPane1.setViewportView(new SistemUtama());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        lbl_rpointA1 = new javax.swing.JLabel();
        fld_px1 = new javax.swing.JTextField();
        fld_py1 = new javax.swing.JTextField();
        lbl_rpointD1 = new javax.swing.JLabel();
        fld_px2 = new javax.swing.JTextField();
        fld_py2 = new javax.swing.JTextField();
        btn_addPointA = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbl_pointA = new javax.swing.JLabel();
        lbl_pointB = new javax.swing.JLabel();
        fld_lx1 = new javax.swing.JTextField();
        fld_ly1 = new javax.swing.JTextField();
        fld_lx2 = new javax.swing.JTextField();
        fld_ly2 = new javax.swing.JTextField();
        btn_addLine = new javax.swing.JButton();
        lbl_pointA1 = new javax.swing.JLabel();
        fld_lx5 = new javax.swing.JTextField();
        fld_ly5 = new javax.swing.JTextField();
        lbl_pointB1 = new javax.swing.JLabel();
        fld_lx6 = new javax.swing.JTextField();
        fld_ly6 = new javax.swing.JTextField();
        lbl_pointA2 = new javax.swing.JLabel();
        fld_lx3 = new javax.swing.JTextField();
        fld_ly3 = new javax.swing.JTextField();
        lbl_pointB2 = new javax.swing.JLabel();
        fld_lx4 = new javax.swing.JTextField();
        fld_ly4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_addRect = new javax.swing.JButton();
        fld_ry1 = new javax.swing.JTextField();
        lbl_rpointB = new javax.swing.JLabel();
        lbl_rpointA = new javax.swing.JLabel();
        fld_rx1 = new javax.swing.JTextField();
        fld_rh1 = new javax.swing.JTextField();
        lbl_rpointD = new javax.swing.JLabel();
        fld_rw1 = new javax.swing.JTextField();
        lbl_rpointC = new javax.swing.JLabel();
        lbl_rpointA2 = new javax.swing.JLabel();
        fld_rx2 = new javax.swing.JTextField();
        lbl_rpointB1 = new javax.swing.JLabel();
        fld_ry2 = new javax.swing.JTextField();
        lbl_rpointC1 = new javax.swing.JLabel();
        fld_rw2 = new javax.swing.JTextField();
        lbl_rpointD2 = new javax.swing.JLabel();
        fld_rh2 = new javax.swing.JTextField();
        lbl_rpointA3 = new javax.swing.JLabel();
        fld_rx3 = new javax.swing.JTextField();
        lbl_rpointB2 = new javax.swing.JLabel();
        fld_ry3 = new javax.swing.JTextField();
        lbl_rpointC2 = new javax.swing.JLabel();
        fld_rw3 = new javax.swing.JTextField();
        lbl_rpointD3 = new javax.swing.JLabel();
        fld_rh3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_tpointA = new javax.swing.JLabel();
        fld_tx1 = new javax.swing.JTextField();
        fld_ty1 = new javax.swing.JTextField();
        lbl_tpointB = new javax.swing.JLabel();
        fld_tx2 = new javax.swing.JTextField();
        fld_ty2 = new javax.swing.JTextField();
        lbl_tpointC = new javax.swing.JLabel();
        fld_tx3 = new javax.swing.JTextField();
        fld_ty3 = new javax.swing.JTextField();
        btn_addTri = new javax.swing.JButton();
        lbl_tpointA1 = new javax.swing.JLabel();
        fld_tx4 = new javax.swing.JTextField();
        fld_ty4 = new javax.swing.JTextField();
        lbl_tpointB1 = new javax.swing.JLabel();
        fld_tx5 = new javax.swing.JTextField();
        fld_ty5 = new javax.swing.JTextField();
        lbl_tpointC1 = new javax.swing.JLabel();
        fld_tx6 = new javax.swing.JTextField();
        fld_ty6 = new javax.swing.JTextField();
        lbl_tpointA2 = new javax.swing.JLabel();
        fld_tx7 = new javax.swing.JTextField();
        fld_ty7 = new javax.swing.JTextField();
        lbl_tpointB2 = new javax.swing.JLabel();
        fld_tx8 = new javax.swing.JTextField();
        fld_ty8 = new javax.swing.JTextField();
        lbl_tpointC2 = new javax.swing.JLabel();
        fld_tx9 = new javax.swing.JTextField();
        fld_ty9 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_ex = new javax.swing.JLabel();
        lbl_ey = new javax.swing.JLabel();
        fld_ex1 = new javax.swing.JTextField();
        fld_ey1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fld_ed1 = new javax.swing.JTextField();
        btn_addElli = new javax.swing.JButton();
        fld_ed3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fld_ey3 = new javax.swing.JTextField();
        lbl_ey1 = new javax.swing.JLabel();
        fld_ex3 = new javax.swing.JTextField();
        lbl_ex1 = new javax.swing.JLabel();
        fld_ed2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fld_ey2 = new javax.swing.JTextField();
        lbl_ey2 = new javax.swing.JLabel();
        fld_ex2 = new javax.swing.JTextField();
        lbl_ex2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_addClipArea = new javax.swing.JButton();
        fld_cymin = new javax.swing.JTextField();
        fld_cxmax = new javax.swing.JTextField();
        fld_cxmin = new javax.swing.JTextField();
        fld_cymax = new javax.swing.JTextField();
        lbl_cxmin = new javax.swing.JLabel();
        lbl_cxmax = new javax.swing.JLabel();
        lbl_cymax = new javax.swing.JLabel();
        lbl_cymin = new javax.swing.JLabel();
        btn_clip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 540));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(480, 480));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel1.setText("CLIPPING");

        btn_clear.setBackground(new java.awt.Color(102, 255, 255));
        btn_clear.setText("HAPUS");
        btn_clear.setFocusable(false);
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_menu.setBackground(new java.awt.Color(102, 255, 255));
        btn_menu.setText("MENU");
        btn_menu.setFocusable(false);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane2.setFocusable(false);
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(220, 230));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lbl_rpointA1.setText("Point A");

        fld_px1.setPreferredSize(new java.awt.Dimension(90, 20));

        fld_py1.setPreferredSize(new java.awt.Dimension(90, 20));

        lbl_rpointD1.setText("Point B");

        fld_px2.setPreferredSize(new java.awt.Dimension(90, 20));

        fld_py2.setPreferredSize(new java.awt.Dimension(90, 20));

        btn_addPointA.setBackground(new java.awt.Color(204, 255, 255));
        btn_addPointA.setText("TAMPILKAN TITIK");
        btn_addPointA.setFocusable(false);
        btn_addPointA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addPointAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btn_addPointA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rpointA1)
                    .addComponent(fld_px1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_py1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rpointD1)
                    .addComponent(fld_py2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_px2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_rpointD1)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_rpointA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_px1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_px2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_py1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fld_py2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addComponent(btn_addPointA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Point", jPanel7);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pointA.setText("Point A1");

        lbl_pointB.setText("Point B1");

        fld_lx1.setToolTipText("input x1");
        fld_lx1.setPreferredSize(new java.awt.Dimension(60, 28));
        fld_lx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_lx1ActionPerformed(evt);
            }
        });

        fld_ly1.setToolTipText("input y1");
        fld_ly1.setPreferredSize(new java.awt.Dimension(60, 28));

        fld_lx2.setToolTipText("input x2");
        fld_lx2.setPreferredSize(new java.awt.Dimension(60, 28));

        fld_ly2.setToolTipText("input y2");
        fld_ly2.setPreferredSize(new java.awt.Dimension(60, 28));

        btn_addLine.setBackground(new java.awt.Color(102, 255, 255));
        btn_addLine.setText("Add Line");
        btn_addLine.setFocusable(false);
        btn_addLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addLineActionPerformed(evt);
            }
        });

        lbl_pointA1.setText("Point A3");

        fld_lx5.setToolTipText("input x1");
        fld_lx5.setPreferredSize(new java.awt.Dimension(60, 28));
        fld_lx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_lx5ActionPerformed(evt);
            }
        });

        fld_ly5.setToolTipText("input y1");
        fld_ly5.setPreferredSize(new java.awt.Dimension(60, 28));

        lbl_pointB1.setText("Point B3");

        fld_lx6.setToolTipText("input x2");
        fld_lx6.setPreferredSize(new java.awt.Dimension(60, 28));

        fld_ly6.setToolTipText("input y2");
        fld_ly6.setPreferredSize(new java.awt.Dimension(60, 28));

        lbl_pointA2.setText("Point A2");

        fld_lx3.setToolTipText("input x1");
        fld_lx3.setPreferredSize(new java.awt.Dimension(60, 28));
        fld_lx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_lx3ActionPerformed(evt);
            }
        });

        fld_ly3.setToolTipText("input y1");
        fld_ly3.setPreferredSize(new java.awt.Dimension(60, 28));

        lbl_pointB2.setText("Point B2");

        fld_lx4.setToolTipText("input x2");
        fld_lx4.setPreferredSize(new java.awt.Dimension(60, 28));

        fld_ly4.setToolTipText("input y2");
        fld_ly4.setPreferredSize(new java.awt.Dimension(60, 28));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fld_ly1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_pointA)
                        .addComponent(fld_lx1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_pointB)
                    .addComponent(fld_lx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ly2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fld_ly3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_pointA2)
                        .addComponent(fld_lx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_pointB2)
                    .addComponent(fld_lx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ly4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fld_ly5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_pointA1)
                        .addComponent(fld_lx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_pointB1)
                    .addComponent(fld_lx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ly6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btn_addLine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(lbl_pointA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fld_lx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fld_ly1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl_pointB)
                            .addGap(13, 13, 13)
                            .addComponent(fld_lx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fld_ly2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(lbl_pointA1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fld_lx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fld_ly5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl_pointB1)
                            .addGap(13, 13, 13)
                            .addComponent(fld_lx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fld_ly6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbl_pointA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_lx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_ly3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_pointB2)
                        .addGap(13, 13, 13)
                        .addComponent(fld_lx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_ly4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_addLine)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Line", jPanel6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_addRect.setBackground(new java.awt.Color(102, 255, 255));
        btn_addRect.setText("Add Rectangle");
        btn_addRect.setFocusable(false);
        btn_addRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addRectActionPerformed(evt);
            }
        });

        fld_ry1.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_ry1.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointB.setText("Y1 Axis");

        lbl_rpointA.setText("X1 Axis");

        fld_rx1.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rx1.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_rh1.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rh1.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointD.setText("Height1");

        fld_rw1.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rw1.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointC.setText("Width1");

        lbl_rpointA2.setText("X2 Axis");

        fld_rx2.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rx2.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointB1.setText("Y2 Axis");

        fld_ry2.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_ry2.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointC1.setText("Width2");

        fld_rw2.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rw2.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointD2.setText("Height2");

        fld_rh2.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rh2.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointA3.setText("X3 Axis");

        fld_rx3.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rx3.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointB2.setText("Y3 Axis");

        fld_ry3.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_ry3.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointC2.setText("Width3");

        fld_rw3.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rw3.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_rpointD3.setText("Height3");

        fld_rh3.setMinimumSize(new java.awt.Dimension(60, 20));
        fld_rh3.setPreferredSize(new java.awt.Dimension(60, 26));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rpointA)
                    .addComponent(fld_rx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_rh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointD)
                    .addComponent(fld_rw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointC)
                    .addComponent(fld_ry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointB))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rpointA2)
                    .addComponent(fld_rx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_rh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointD2)
                    .addComponent(fld_rw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointC1)
                    .addComponent(fld_ry2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rpointA3)
                    .addComponent(fld_rx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_rh3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointD3)
                    .addComponent(fld_rw3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointC2)
                    .addComponent(fld_ry3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rpointB2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_addRect)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_rpointA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_rx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_rpointB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_rpointC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_rw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_rpointD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_rh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_rpointA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_rx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_rpointB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ry2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_rpointC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_rw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_rpointD2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_rh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_rpointA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_rx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_rpointB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ry3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_rpointC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_rw3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_rpointD3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_rh3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addRect)
                .addGap(23, 23, 23))
        );

        jTabbedPane2.addTab("Rectangle", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_tpointA.setText("Point A1");

        fld_tx1.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty1.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_tpointB.setText("Point B1");

        fld_tx2.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty2.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_tpointC.setText("Point C1");

        fld_tx3.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty3.setPreferredSize(new java.awt.Dimension(60, 26));

        btn_addTri.setBackground(new java.awt.Color(102, 255, 255));
        btn_addTri.setText("Add Triangle");
        btn_addTri.setFocusable(false);
        btn_addTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addTriActionPerformed(evt);
            }
        });

        lbl_tpointA1.setText("Point A2");

        fld_tx4.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty4.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_tpointB1.setText("Point B2");

        fld_tx5.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty5.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_tpointC1.setText("Point C2");

        fld_tx6.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty6.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_tpointA2.setText("Point A3");

        fld_tx7.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty7.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_tpointB2.setText("Point B3");

        fld_tx8.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty8.setPreferredSize(new java.awt.Dimension(60, 26));

        lbl_tpointC2.setText("Point C3");

        fld_tx9.setPreferredSize(new java.awt.Dimension(60, 26));

        fld_ty9.setPreferredSize(new java.awt.Dimension(60, 26));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tpointA)
                    .addComponent(fld_tx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tpointB)
                    .addComponent(fld_tx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tpointC)
                    .addComponent(fld_ty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_tx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tpointA1)
                    .addComponent(fld_tx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ty4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tpointB1)
                    .addComponent(fld_tx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tpointC1)
                    .addComponent(fld_ty6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_tx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ty5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_tpointA2)
                    .addComponent(fld_tx7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tpointB2)
                    .addComponent(fld_tx8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tpointC2)
                    .addComponent(fld_ty9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_tx9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_ty8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btn_addTri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_tpointA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tpointB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tpointC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_tpointA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tpointB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tpointC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_tpointA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tpointB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tpointC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_tx9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ty9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addTri)
                .addGap(13, 13, 13))
        );

        jTabbedPane2.addTab("Triangle", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbl_ex.setText("X Axis");

        lbl_ey.setText("Y Axis");

        fld_ex1.setPreferredSize(new java.awt.Dimension(90, 26));

        fld_ey1.setPreferredSize(new java.awt.Dimension(90, 26));

        jLabel10.setText("Diameter");

        fld_ed1.setPreferredSize(new java.awt.Dimension(90, 26));

        btn_addElli.setBackground(new java.awt.Color(102, 255, 255));
        btn_addElli.setText("Add Ellipse");
        btn_addElli.setFocusable(false);
        btn_addElli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addElliActionPerformed(evt);
            }
        });

        fld_ed3.setPreferredSize(new java.awt.Dimension(90, 26));

        jLabel11.setText("Diameter");

        fld_ey3.setPreferredSize(new java.awt.Dimension(90, 26));

        lbl_ey1.setText("Y Axis");

        fld_ex3.setPreferredSize(new java.awt.Dimension(90, 26));

        lbl_ex1.setText("X Axis");

        fld_ed2.setPreferredSize(new java.awt.Dimension(90, 26));

        jLabel12.setText("Diameter");

        fld_ey2.setPreferredSize(new java.awt.Dimension(90, 26));

        lbl_ey2.setText("Y Axis");

        fld_ex2.setPreferredSize(new java.awt.Dimension(90, 26));

        lbl_ex2.setText("X Axis");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fld_ed1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fld_ey1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(lbl_ex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ey, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_ex1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fld_ed2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fld_ey2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lbl_ex2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ey2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_ex2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fld_ed3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fld_ey3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lbl_ex1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ey1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_ex3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_addElli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_ex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_ex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lbl_ey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_ex1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_ex3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lbl_ey1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ey3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ed3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_ex2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_ex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lbl_ey2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_ed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_addElli)
                .addGap(39, 39, 39))
        );

        jTabbedPane2.addTab("Ellipse", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(220, 120));

        btn_addClipArea.setBackground(new java.awt.Color(102, 255, 255));
        btn_addClipArea.setText("Clip Area");
        btn_addClipArea.setFocusable(false);
        btn_addClipArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addClipAreaActionPerformed(evt);
            }
        });

        fld_cymin.setPreferredSize(new java.awt.Dimension(60, 20));

        fld_cxmax.setPreferredSize(new java.awt.Dimension(60, 20));

        fld_cxmin.setPreferredSize(new java.awt.Dimension(60, 20));
        fld_cxmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_cxminActionPerformed(evt);
            }
        });

        fld_cymax.setPreferredSize(new java.awt.Dimension(60, 20));
        fld_cymax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_cymaxActionPerformed(evt);
            }
        });

        lbl_cxmin.setText("X Min");

        lbl_cxmax.setText("X Max");

        lbl_cymax.setText("Y Min");

        lbl_cymin.setText("Y Max");

        btn_clip.setBackground(new java.awt.Color(102, 255, 255));
        btn_clip.setText("Clip");
        btn_clip.setFocusable(false);
        btn_clip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(fld_cxmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fld_cxmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_cxmin)
                                .addGap(44, 44, 44)
                                .addComponent(lbl_cxmax)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbl_cymax)
                                .addGap(42, 42, 42)
                                .addComponent(lbl_cymin))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fld_cymin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fld_cymax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_addClipArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clip)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cxmin)
                    .addComponent(lbl_cxmax)
                    .addComponent(lbl_cymax)
                    .addComponent(lbl_cymin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fld_cxmax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fld_cymax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fld_cxmin, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(fld_cymin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addClipArea)
                    .addComponent(btn_clip))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_clear)
                                        .addGap(160, 160, 160)
                                        .addComponent(btn_menu))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(123, 123, 123))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear)
                            .addComponent(btn_menu))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("shape");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        jScrollPane1.setViewportView(new SistemUtama());
        state = 0;
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_addRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addRectActionPerformed
        try {
            x1 = Integer.parseInt(fld_rx1.getText());
            y1 = Integer.parseInt(fld_ry1.getText());
            x2 = Integer.parseInt(fld_rw1.getText());//w1
            y2 = Integer.parseInt(fld_rh1.getText());//h1
            x3 = Integer.parseInt(fld_rx2.getText());
            y3 = Integer.parseInt(fld_ry2.getText());
            x4 = Integer.parseInt(fld_rw2.getText());//w2
            y4 = Integer.parseInt(fld_rh2.getText());//h2
            x5 = Integer.parseInt(fld_rx3.getText());
            y5 = Integer.parseInt(fld_ry3.getText());
            x6 = Integer.parseInt(fld_rw3.getText());//w3
            y6 = Integer.parseInt(fld_rh3.getText());//h3
            int x[] = {x1, x2, x3, x4, x5, x6};
            int y[] = {y1, y2, y3, y4, y5, y6};
            jScrollPane1.setViewportView(new SistemUtama(x, y, 31));
            state = 3;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
        }
    }//GEN-LAST:event_btn_addRectActionPerformed

    private void btn_addTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addTriActionPerformed
        try {
            x1 = Integer.parseInt(fld_tx1.getText());
            x2 = Integer.parseInt(fld_tx2.getText());
            x3 = Integer.parseInt(fld_tx3.getText());
            y1 = Integer.parseInt(fld_ty1.getText());
            y2 = Integer.parseInt(fld_ty2.getText());
            y3 = Integer.parseInt(fld_ty3.getText());
            x4 = Integer.parseInt(fld_tx4.getText());
            x5 = Integer.parseInt(fld_tx5.getText());
            x6 = Integer.parseInt(fld_tx6.getText());
            y4 = Integer.parseInt(fld_ty4.getText());
            y5 = Integer.parseInt(fld_ty5.getText());
            y6 = Integer.parseInt(fld_ty6.getText());
            int x7 = Integer.parseInt(fld_tx7.getText());
            int x8 = Integer.parseInt(fld_tx8.getText());
            int x9 = Integer.parseInt(fld_tx9.getText());
            int y7 = Integer.parseInt(fld_ty7.getText());
            int y8 = Integer.parseInt(fld_ty8.getText());
            int y9 = Integer.parseInt(fld_ty9.getText());
            int x[] = {x1 * grid + wSize, x2 * grid + wSize, x3 * grid + wSize, x4 * grid + wSize, x5 * grid + wSize,
                x6 * grid + wSize, x7 * grid + wSize, x8 * grid + wSize, x9 * grid + wSize};
            int y[] = {wSize - grid * y1, wSize - grid * y2, wSize - grid * y3, wSize - grid * y4, wSize - grid * y5,
                wSize - grid * y6, wSize - grid * y7, wSize - grid * y8, wSize - grid * y9};
            jScrollPane1.setViewportView(new SistemUtama(x, y, 32));
            state = 4;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
        }
    }//GEN-LAST:event_btn_addTriActionPerformed

    private void btn_addElliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addElliActionPerformed
        try {
            x1 = Integer.parseInt(fld_ex1.getText());
            y1 = Integer.parseInt(fld_ey1.getText());
            d1 = Integer.parseInt(fld_ed1.getText());
            x2 = Integer.parseInt(fld_ex2.getText());
            y2 = Integer.parseInt(fld_ey2.getText());
            d2 = Integer.parseInt(fld_ed2.getText());
            x3 = Integer.parseInt(fld_ex3.getText());
            y3 = Integer.parseInt(fld_ey3.getText());
            d3 = Integer.parseInt(fld_ed3.getText());
            int x[] = {x1, x2, x3, d1, d2, d3};
            int y[] = {y1, y2, y3};
            jScrollPane1.setViewportView(new SistemUtama(x, y, 33));
            state = 5;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
        }
    }//GEN-LAST:event_btn_addElliActionPerformed

    private void btn_addClipAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addClipAreaActionPerformed
        int xmin = Integer.parseInt(fld_cxmin.getText());
        int xmax = Integer.parseInt(fld_cxmax.getText());
        int ymin = Integer.parseInt(fld_cymin.getText());
        int ymax = Integer.parseInt(fld_cymax.getText());
        int c[] = {xmin, xmax, ymin, ymax};
        if (state == 1) {//point
            try {
                x1 = Integer.parseInt(fld_px1.getText());
                y1 = Integer.parseInt(fld_py1.getText());
                x2 = Integer.parseInt(fld_px2.getText());
                y2 = Integer.parseInt(fld_py2.getText());
                int x[] = {x1, x2};
                int y[] = {y1, y2};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 29, 1));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 2) {//line
            try {
                x1 = Integer.parseInt(fld_lx1.getText());
                y1 = Integer.parseInt(fld_ly1.getText());
                x2 = Integer.parseInt(fld_lx2.getText());
                y2 = Integer.parseInt(fld_ly2.getText());
                x3 = Integer.parseInt(fld_lx3.getText());
                y3 = Integer.parseInt(fld_ly3.getText());
                x4 = Integer.parseInt(fld_lx4.getText());
                y4 = Integer.parseInt(fld_ly4.getText());
                x5 = Integer.parseInt(fld_lx5.getText());
                y5 = Integer.parseInt(fld_ly5.getText());
                x6 = Integer.parseInt(fld_lx6.getText());
                y6 = Integer.parseInt(fld_ly6.getText());
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 30, 1));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 3) {//rectangle
            try {
                x1 = Integer.parseInt(fld_rx1.getText());
                y1 = Integer.parseInt(fld_ry1.getText());
                x2 = Integer.parseInt(fld_rw1.getText());//w1
                y2 = Integer.parseInt(fld_rh1.getText());//h1
                x3 = Integer.parseInt(fld_rx2.getText());
                y3 = Integer.parseInt(fld_ry2.getText());
                x4 = Integer.parseInt(fld_rw2.getText());//w2
                y4 = Integer.parseInt(fld_rh2.getText());//h2
                x5 = Integer.parseInt(fld_rx3.getText());
                y5 = Integer.parseInt(fld_ry3.getText());
                x6 = Integer.parseInt(fld_rw3.getText());//w3
                y6 = Integer.parseInt(fld_rh3.getText());//h3
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 31, 1));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 4) {//triagle
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());
                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                x4 = Integer.parseInt(fld_tx4.getText());
                x5 = Integer.parseInt(fld_tx5.getText());
                x6 = Integer.parseInt(fld_tx6.getText());
                y4 = Integer.parseInt(fld_ty4.getText());
                y5 = Integer.parseInt(fld_ty5.getText());
                y6 = Integer.parseInt(fld_ty6.getText());
                int x7 = Integer.parseInt(fld_tx7.getText());
                int x8 = Integer.parseInt(fld_tx8.getText());
                int x9 = Integer.parseInt(fld_tx9.getText());
                int y7 = Integer.parseInt(fld_ty7.getText());
                int y8 = Integer.parseInt(fld_ty8.getText());
                int y9 = Integer.parseInt(fld_ty9.getText());
                int x[] = {x1 * grid + wSize, x2 * grid + wSize, x3 * grid + wSize, x4 * grid + wSize, x5 * grid + wSize,
                    x6 * grid + wSize, x7 * grid + wSize, x8 * grid + wSize, x9 * grid + wSize};
                int y[] = {wSize - grid * y1, wSize - grid * y2, wSize - grid * y3, wSize - grid * y4, wSize - grid * y5,
                    wSize - grid * y6, wSize - grid * y7, wSize - grid * y8, wSize - grid * y9};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 32, 1));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 5) {//ellipse
            try {
                x1 = Integer.parseInt(fld_ex1.getText());
                y1 = Integer.parseInt(fld_ey1.getText());
                d1 = Integer.parseInt(fld_ed1.getText());
                x2 = Integer.parseInt(fld_ex2.getText());
                y2 = Integer.parseInt(fld_ey2.getText());
                d2 = Integer.parseInt(fld_ed2.getText());
                x3 = Integer.parseInt(fld_ex3.getText());
                y3 = Integer.parseInt(fld_ey3.getText());
                d3 = Integer.parseInt(fld_ed3.getText());
                int x[] = {x1, x2, x3, d1, d2, d3};
                int y[] = {y1, y2, y3};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 33, 1));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_addClipAreaActionPerformed

    private void btn_clipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clipActionPerformed
        int xmin = Integer.parseInt(fld_cxmin.getText());
        int xmax = Integer.parseInt(fld_cxmax.getText());
        int ymin = Integer.parseInt(fld_cymin.getText());
        int ymax = Integer.parseInt(fld_cymax.getText());
        int c[] = {xmin, xmax, ymin, ymax};
        if (state == 1) {//point
            try {
                x1 = Integer.parseInt(fld_px1.getText());
                y1 = Integer.parseInt(fld_py1.getText());
                x2 = Integer.parseInt(fld_px2.getText());
                y2 = Integer.parseInt(fld_py2.getText());
                int x[] = {x1, x2};
                int y[] = {y1, y2};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 29, 2));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 2) {//line
            try {
                x1 = Integer.parseInt(fld_lx1.getText());
                y1 = Integer.parseInt(fld_ly1.getText());
                x2 = Integer.parseInt(fld_lx2.getText());
                y2 = Integer.parseInt(fld_ly2.getText());
                x3 = Integer.parseInt(fld_lx3.getText());
                y3 = Integer.parseInt(fld_ly3.getText());
                x4 = Integer.parseInt(fld_lx4.getText());
                y4 = Integer.parseInt(fld_ly4.getText());
                x5 = Integer.parseInt(fld_lx5.getText());
                y5 = Integer.parseInt(fld_ly5.getText());
                x6 = Integer.parseInt(fld_lx6.getText());
                y6 = Integer.parseInt(fld_ly6.getText());
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 30, 2));
            } catch (Exception e) {
            }
            JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
        }
        if (state == 3) {//rectangle
            try {
                x1 = Integer.parseInt(fld_rx1.getText());
                y1 = Integer.parseInt(fld_ry1.getText());
                x2 = Integer.parseInt(fld_rw1.getText());//w1
                y2 = Integer.parseInt(fld_rh1.getText());//h1
                x3 = Integer.parseInt(fld_rx2.getText());
                y3 = Integer.parseInt(fld_ry2.getText());
                x4 = Integer.parseInt(fld_rw2.getText());//w2
                y4 = Integer.parseInt(fld_rh2.getText());//h2
                x5 = Integer.parseInt(fld_rx3.getText());
                y5 = Integer.parseInt(fld_ry3.getText());
                x6 = Integer.parseInt(fld_rw1.getText());//w3
                y6 = Integer.parseInt(fld_rh1.getText());//h3
                int x[] = {x1, x2, x3, x4, x5, x6};
                int y[] = {y1, y2, y3, y4, y5, y6};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 31, 2));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 4) {//triangle
            try {
                x1 = Integer.parseInt(fld_tx1.getText());
                x2 = Integer.parseInt(fld_tx2.getText());
                x3 = Integer.parseInt(fld_tx3.getText());
                y1 = Integer.parseInt(fld_ty1.getText());
                y2 = Integer.parseInt(fld_ty2.getText());
                y3 = Integer.parseInt(fld_ty3.getText());
                x4 = Integer.parseInt(fld_tx4.getText());
                x5 = Integer.parseInt(fld_tx5.getText());
                x6 = Integer.parseInt(fld_tx6.getText());
                y4 = Integer.parseInt(fld_ty4.getText());
                y5 = Integer.parseInt(fld_ty5.getText());
                y6 = Integer.parseInt(fld_ty6.getText());
                int x7 = Integer.parseInt(fld_tx7.getText());
                int x8 = Integer.parseInt(fld_tx8.getText());
                int x9 = Integer.parseInt(fld_tx9.getText());
                int y7 = Integer.parseInt(fld_ty7.getText());
                int y8 = Integer.parseInt(fld_ty8.getText());
                int y9 = Integer.parseInt(fld_ty9.getText());
                int x[] = {x1 * grid + wSize, x2 * grid + wSize, x3 * grid + wSize, x4 * grid + wSize, x5 * grid + wSize,
                    x6 * grid + wSize, x7 * grid + wSize, x8 * grid + wSize, x9 * grid + wSize};
                int y[] = {wSize - grid * y1, wSize - grid * y2, wSize - grid * y3, wSize - grid * y4, wSize - grid * y5,
                    wSize - grid * y6, wSize - grid * y7, wSize - grid * y8, wSize - grid * y9};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 32, 2));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
        if (state == 5) {//ellipse
            try {
                x1 = Integer.parseInt(fld_ex1.getText());
                y1 = Integer.parseInt(fld_ey1.getText());
                d1 = Integer.parseInt(fld_ed1.getText());
                x2 = Integer.parseInt(fld_ex2.getText());
                y2 = Integer.parseInt(fld_ey2.getText());
                d2 = Integer.parseInt(fld_ed2.getText());
                x3 = Integer.parseInt(fld_ex3.getText());
                y3 = Integer.parseInt(fld_ey3.getText());
                d3 = Integer.parseInt(fld_ed3.getText());
                int x[] = {x1, x2, x3, d1, d2, d3};
                int y[] = {y1, y2, y3};
                jScrollPane1.setViewportView(new SistemUtama(x, y, c, 33, 2));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lengkapi Form yang Kosong!");
            }
        }
    }//GEN-LAST:event_btn_clipActionPerformed

    private void fld_lx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_lx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_lx1ActionPerformed

    private void btn_addLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addLineActionPerformed
        try {
            x1 = Integer.parseInt(fld_lx1.getText());
            y1 = Integer.parseInt(fld_ly1.getText());
            x2 = Integer.parseInt(fld_lx2.getText());
            y2 = Integer.parseInt(fld_ly2.getText());
            x3 = Integer.parseInt(fld_lx3.getText());
            y3 = Integer.parseInt(fld_ly3.getText());
            x4 = Integer.parseInt(fld_lx4.getText());
            y4 = Integer.parseInt(fld_ly4.getText());
            x5 = Integer.parseInt(fld_lx5.getText());
            y5 = Integer.parseInt(fld_ly5.getText());
            x6 = Integer.parseInt(fld_lx6.getText());
            y6 = Integer.parseInt(fld_ly6.getText());
            int x[] = {x1, x2, x3, x4, x5, x6};
            int y[] = {y1, y2, y3, y4, y5, y6};
            jScrollPane1.setViewportView(new SistemUtama(x, y, 30));
            state = 2;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_addLineActionPerformed

    private void fld_lx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_lx5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_lx5ActionPerformed

    private void fld_lx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_lx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_lx3ActionPerformed

    private void btn_addPointAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addPointAActionPerformed
        try {
            x1 = Integer.parseInt(fld_px1.getText());
            y1 = Integer.parseInt(fld_py1.getText());
            x2 = Integer.parseInt(fld_px2.getText());
            y2 = Integer.parseInt(fld_py2.getText());
            jScrollPane1.setViewportView(new SistemUtama(x1, y1, x2, y2, 1));
            state = 1;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_addPointAActionPerformed

    private void fld_cymaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_cymaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_cymaxActionPerformed

    private void fld_cxminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_cxminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_cxminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addClipArea;
    private javax.swing.JButton btn_addElli;
    private javax.swing.JButton btn_addLine;
    private javax.swing.JButton btn_addPointA;
    private javax.swing.JButton btn_addRect;
    private javax.swing.JButton btn_addTri;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_clip;
    private javax.swing.JButton btn_menu;
    private javax.swing.JTextField fld_cxmax;
    private javax.swing.JTextField fld_cxmin;
    private javax.swing.JTextField fld_cymax;
    private javax.swing.JTextField fld_cymin;
    private javax.swing.JTextField fld_ed1;
    private javax.swing.JTextField fld_ed2;
    private javax.swing.JTextField fld_ed3;
    private javax.swing.JTextField fld_ex1;
    private javax.swing.JTextField fld_ex2;
    private javax.swing.JTextField fld_ex3;
    private javax.swing.JTextField fld_ey1;
    private javax.swing.JTextField fld_ey2;
    private javax.swing.JTextField fld_ey3;
    private javax.swing.JTextField fld_lx1;
    private javax.swing.JTextField fld_lx2;
    private javax.swing.JTextField fld_lx3;
    private javax.swing.JTextField fld_lx4;
    private javax.swing.JTextField fld_lx5;
    private javax.swing.JTextField fld_lx6;
    private javax.swing.JTextField fld_ly1;
    private javax.swing.JTextField fld_ly2;
    private javax.swing.JTextField fld_ly3;
    private javax.swing.JTextField fld_ly4;
    private javax.swing.JTextField fld_ly5;
    private javax.swing.JTextField fld_ly6;
    private javax.swing.JTextField fld_px1;
    private javax.swing.JTextField fld_px2;
    private javax.swing.JTextField fld_py1;
    private javax.swing.JTextField fld_py2;
    private javax.swing.JTextField fld_rh1;
    private javax.swing.JTextField fld_rh2;
    private javax.swing.JTextField fld_rh3;
    private javax.swing.JTextField fld_rw1;
    private javax.swing.JTextField fld_rw2;
    private javax.swing.JTextField fld_rw3;
    private javax.swing.JTextField fld_rx1;
    private javax.swing.JTextField fld_rx2;
    private javax.swing.JTextField fld_rx3;
    private javax.swing.JTextField fld_ry1;
    private javax.swing.JTextField fld_ry2;
    private javax.swing.JTextField fld_ry3;
    private javax.swing.JTextField fld_tx1;
    private javax.swing.JTextField fld_tx2;
    private javax.swing.JTextField fld_tx3;
    private javax.swing.JTextField fld_tx4;
    private javax.swing.JTextField fld_tx5;
    private javax.swing.JTextField fld_tx6;
    private javax.swing.JTextField fld_tx7;
    private javax.swing.JTextField fld_tx8;
    private javax.swing.JTextField fld_tx9;
    private javax.swing.JTextField fld_ty1;
    private javax.swing.JTextField fld_ty2;
    private javax.swing.JTextField fld_ty3;
    private javax.swing.JTextField fld_ty4;
    private javax.swing.JTextField fld_ty5;
    private javax.swing.JTextField fld_ty6;
    private javax.swing.JTextField fld_ty7;
    private javax.swing.JTextField fld_ty8;
    private javax.swing.JTextField fld_ty9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_cxmax;
    private javax.swing.JLabel lbl_cxmin;
    private javax.swing.JLabel lbl_cymax;
    private javax.swing.JLabel lbl_cymin;
    private javax.swing.JLabel lbl_ex;
    private javax.swing.JLabel lbl_ex1;
    private javax.swing.JLabel lbl_ex2;
    private javax.swing.JLabel lbl_ey;
    private javax.swing.JLabel lbl_ey1;
    private javax.swing.JLabel lbl_ey2;
    private javax.swing.JLabel lbl_pointA;
    private javax.swing.JLabel lbl_pointA1;
    private javax.swing.JLabel lbl_pointA2;
    private javax.swing.JLabel lbl_pointB;
    private javax.swing.JLabel lbl_pointB1;
    private javax.swing.JLabel lbl_pointB2;
    private javax.swing.JLabel lbl_rpointA;
    private javax.swing.JLabel lbl_rpointA1;
    private javax.swing.JLabel lbl_rpointA2;
    private javax.swing.JLabel lbl_rpointA3;
    private javax.swing.JLabel lbl_rpointB;
    private javax.swing.JLabel lbl_rpointB1;
    private javax.swing.JLabel lbl_rpointB2;
    private javax.swing.JLabel lbl_rpointC;
    private javax.swing.JLabel lbl_rpointC1;
    private javax.swing.JLabel lbl_rpointC2;
    private javax.swing.JLabel lbl_rpointD;
    private javax.swing.JLabel lbl_rpointD1;
    private javax.swing.JLabel lbl_rpointD2;
    private javax.swing.JLabel lbl_rpointD3;
    private javax.swing.JLabel lbl_tpointA;
    private javax.swing.JLabel lbl_tpointA1;
    private javax.swing.JLabel lbl_tpointA2;
    private javax.swing.JLabel lbl_tpointB;
    private javax.swing.JLabel lbl_tpointB1;
    private javax.swing.JLabel lbl_tpointB2;
    private javax.swing.JLabel lbl_tpointC;
    private javax.swing.JLabel lbl_tpointC1;
    private javax.swing.JLabel lbl_tpointC2;
    // End of variables declaration//GEN-END:variables
}
